### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Wikunia** [roboes/neobroker-portfolio-importer#1]
I get lines like this:
```
2024-09-13,Investments,Scalable Capital,iShares Core EURO STOXX 50 (Dist),IE0008471009,,4.44137 €
```
which is neither the amount it's currently worth which is roughly 49€ nor is it how much I invested in it. Also the number of shares is missing.

**Comment by roboes** [comment]
Hi @Wikunia,

Apologies for the delayed response - looks like the email notifications for new issues on this repository were not activated.

I’ve tested the script on Scalable Capital, and it’s working as expected. Could you please test it again with the latest versions of [neobroker-portfolio-importer.py](https://github.com/roboes/neobroker-portfolio-importer/blob/main/neobroker-portfolio-importer.py) and [requirements-packages.py](https://github.com/roboes/neobroker-portfolio-importer/blob/main/requirements-packages.py)?

**Comment by roboes** [comment]
Hi @Wikunia,

I have just updated the logic for retrieving the shares count for Scalable Capital.

It should now work as expected.
